# SPDX-FileCopyrightText: 2026 Contributors to ddc-ci-daemons <https://github.com/digitaltrails/ddc-ci-daemons>
# SPDX-License-Identifier: GPL-2.0-or-later
[package]
name = "ddc-ci-dbus"
version = "0.1.0"
edition = "2024"

[dependencies]
ddcutil-backend = { path = "../ddcutil-backend" }
zbus = { version = "5", features = ["blocking"] }
base64 = "0.21.7"
log = "0.4"
env_logger = "0.11"